import { Initiative } from './types';

export const initiatives: Initiative[] = [
  {
    id: 1,
    title: "Censo de Mascotas",
    shortDescription: "Registro actualizado de animales domésticos.",
    fullDescription: "Implementación de un formulario digital y físico para registrar todas las mascotas del conjunto. Incluye entrega de carnet de identificación y revisión de vacunas para asegurar la salubridad en áreas comunes.",
    budget: 50,
    timeline: "Q1 2026 (Enero)",
    priority: "Alta",
    category: "Gestión",
    icon: "Dog",
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 2,
    title: "Censo de Personas",
    shortDescription: "Actualización de base de datos de residentes.",
    fullDescription: "Levantamiento de información de propietarios y arrendatarios para mejorar la seguridad y control de accesos. Fundamental para la emisión de nuevos tags vehiculares y peatonales.",
    budget: 80,
    timeline: "Q1 2026 (Febrero)",
    priority: "Alta",
    category: "Gestión",
    icon: "Users",
    imageUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 3,
    title: "Botiquín para Guardias",
    shortDescription: "Equipamiento de primeros auxilios en garita.",
    fullDescription: "Adquisición de un botiquín de primeros auxilios tipo A para la garita principal, incluyendo tensiómetro, oxímetro, vendas, antisépticos y capacitación básica al personal de seguridad.",
    budget: 180,
    timeline: "Inmediato",
    priority: "Urgente",
    category: "Seguridad",
    icon: "BriefcaseMedical",
    imageUrl: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 4,
    title: "Obsequios Especiales",
    shortDescription: "Detalles para Navidad y Día de la Madre/Padre.",
    fullDescription: "Presupuesto asignado para pequeños presentes comunitarios durante fechas festivas clave (Navidad, Día de la Madre/Padre) para fomentar la integración vecinal.",
    budget: 600,
    timeline: "Anual (Dic/Mayo/Junio)",
    priority: "Media",
    category: "Social",
    icon: "Gift",
    imageUrl: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 5,
    title: "Bocaditos Reuniones",
    shortDescription: "Catering ligero para asambleas.",
    fullDescription: "Fondo para café, agua y bocaditos ligeros durante las asambleas generales y reuniones de directiva para mejorar la asistencia y ambiente.",
    budget: 200,
    timeline: "Recurrente",
    priority: "Baja",
    category: "Social",
    icon: "Coffee",
    imageUrl: "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 6,
    title: "Jardinería Malla Exterior",
    shortDescription: "Mejora visual del perímetro.",
    fullDescription: "Sembrado de enredaderas y plantas ornamentales a lo largo de la malla perimetral exterior para mejorar la estética del conjunto y privacidad.",
    budget: 850,
    timeline: "Q2 2026",
    priority: "Media",
    category: "Infraestructura",
    icon: "Flower2",
    imageUrl: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 7,
    title: "Jornadas para Mascotas",
    shortDescription: "Vacunación y adiestramiento básico.",
    fullDescription: "Coordinación con veterinarias locales para realizar campañas de desparasitación y tips de comportamiento dentro del conjunto un fin de semana.",
    budget: 150,
    timeline: "Q3 2026",
    priority: "Baja",
    category: "Social",
    icon: "Bone",
    imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 8,
    title: "Tardes Lúdicas",
    shortDescription: "Actividades para niños y adultos mayores.",
    fullDescription: "Organización trimestral de tardes de juegos, cine al aire libre o bailoterapia para integrar a los diferentes grupos etarios del conjunto.",
    budget: 400,
    timeline: "Trimestral",
    priority: "Media",
    category: "Social",
    icon: "Gamepad2",
    imageUrl: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 9,
    title: "Techar la Piscina",
    shortDescription: "Estructura para climatización y uso continuo.",
    fullDescription: "Instalación de cubierta de policarbonato y estructura metálica para la piscina. Proyecto de mayor envergadura que permitirá el uso de la piscina en días fríos o lluviosos característicos de Quito.",
    budget: 10500,
    timeline: "Q4 2026 - Q1 2027",
    priority: "Alta",
    category: "Infraestructura",
    icon: "Waves",
    imageUrl: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 10,
    title: "Sensores de Luz",
    shortDescription: "Ahorro energético en baños y salón.",
    fullDescription: "Instalación de sensores de movimiento en baños comunales y salón social para reducir el consumo eléctrico innecesario.",
    budget: 350,
    timeline: "Q2 2026",
    priority: "Alta",
    category: "Infraestructura",
    icon: "Zap",
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 11,
    title: "Televisor y Soporte",
    shortDescription: "TV de 65 pulgadas para el Salón Social.",
    fullDescription: "Adquisición de Smart TV 65'' y soporte de pared para el salón comunal, útil para presentaciones, partidos de fútbol y eventos sociales.",
    budget: 650,
    timeline: "Q2 2026",
    priority: "Media",
    category: "Infraestructura",
    icon: "Tv",
    imageUrl: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 12,
    title: "Nevera Pequeña",
    shortDescription: "Equipamiento para cocina del salón.",
    fullDescription: "Compra de un refrigerador pequeño (minibar o 10 pies) para mantener bebidas y alimentos frescos durante eventos en el salón social.",
    budget: 320,
    timeline: "Q2 2026",
    priority: "Media",
    category: "Infraestructura",
    icon: "Refrigerator",
    imageUrl: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 13,
    title: "Proyector",
    shortDescription: "Equipo visual para asambleas.",
    fullDescription: "Adquisición de proyector HD de alta luminosidad para facilitar la presentación de informes económicos y propuestas en las asambleas nocturnas.",
    budget: 550,
    timeline: "Q2 2026",
    priority: "Alta",
    category: "Gestión",
    icon: "Projector",
    imageUrl: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 14,
    title: "Amplificación",
    shortDescription: "Micrófono y parlante activo.",
    fullDescription: "Sistema de audio portátil (Parlante 15'' + Micrófono inalámbrico) para asegurar que todos los asistentes escuchen claramente en las asambleas.",
    budget: 400,
    timeline: "Q2 2026",
    priority: "Alta",
    category: "Gestión",
    icon: "Mic2",
    imageUrl: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 15,
    title: "Cambio de Señaléticas",
    shortDescription: "Renovación visual interna.",
    fullDescription: "Reemplazo de letreros deteriorados (Límite de velocidad, No estacionar, Uso de áreas) por material reflectivo y estandarizado.",
    budget: 350,
    timeline: "Q3 2026",
    priority: "Media",
    category: "Infraestructura",
    icon: "Signpost",
    imageUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 16,
    title: "Contenedores y Pintura",
    shortDescription: "Mantenimiento de casetas de basura.",
    fullDescription: "Adquisición de nuevos contenedores diferenciados para reciclaje y pintura impermeabilizante para las casetas de acopio de basura.",
    budget: 1200,
    timeline: "Q3 2026",
    priority: "Alta",
    category: "Infraestructura",
    icon: "PaintBucket",
    imageUrl: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 17,
    title: "Espejos Gimnasio",
    shortDescription: "Mejora del área de pesas.",
    fullDescription: "Instalación de espejos de pared a pared en el área de gimnasio y compra de colchonetas nuevas.",
    budget: 750,
    timeline: "Q3 2026",
    priority: "Baja",
    category: "Infraestructura",
    icon: "Dumbbell",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 18,
    title: "Limpieza Alcantarillado",
    shortDescription: "Mantenimiento preventivo anual.",
    fullDescription: "Contratación de hidro-cleaner para limpieza profunda de sumideros y cajas de revisión antes de la temporada invernal fuerte.",
    budget: 600,
    timeline: "Q4 2026",
    priority: "Urgente",
    category: "Infraestructura",
    icon: "Droplets",
    imageUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 19,
    title: "Poda de Árboles",
    shortDescription: "Mantenimiento de arbolado exterior.",
    fullDescription: "Poda técnica y de formación de los árboles ubicados en la zona exterior del conjunto para mejorar la visibilidad, seguridad y salud de las especies vegetales.",
    budget: 300,
    timeline: "Q2 2026",
    priority: "Media",
    category: "Infraestructura",
    icon: "Trees",
    imageUrl: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 20,
    title: "Buzón Digital de Sugerencias",
    shortDescription: "Plataforma para reclamos y sugerencias.",
    fullDescription: "Implementación de un sistema digital accesible vía código QR y web para que los copropietarios puedan registrar sus dudas, reclamos y sugerencias de forma organizada y con seguimiento administrativo.",
    budget: 120,
    timeline: "Q2 2026",
    priority: "Media",
    category: "Gestión",
    icon: "Mail",
    imageUrl: "https://images.unsplash.com/photo-1596524430615-b46475ddff6e?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 21,
    title: "Alquiler Parcial Zona BBQ",
    shortDescription: "Uso independiente de la parrilla.",
    fullDescription: "Modificación del reglamento y sistema de reservas para permitir el alquiler exclusivo de la zona BBQ sin necesidad de arrendar la totalidad del salón comunal, reduciendo costos para el vecino.",
    budget: 50,
    timeline: "Q1 2026",
    priority: "Alta",
    category: "Gestión",
    icon: "Flame",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 22,
    title: "Bloqueo Accesos a Morosos",
    shortDescription: "Restricción de accesos por mora.",
    fullDescription: "Actualización del sistema de control de accesos para permitir el bloqueo automático de tags y tarjetas en puertas peatonales y vehiculares a copropietarios con más de 3 alícuotas vencidas.",
    budget: 450,
    timeline: "Q1 2026",
    priority: "Urgente",
    category: "Seguridad",
    icon: "ShieldOff",
    imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=80"
  }
];